# Generated by Django 3.0.5 on 2021-01-19 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('jvpm', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_register.Especialidades')),
            ],
        ),
    ]
